apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: github-repository-secret
  namespace: argocd
type: Opaque
data:
  sshPrivateKey: "LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNBZFpCYytlU1VXTzBQeUY5Qk0rbTRDVGZnS2ozb3lheDRwaGJwSHpiSk9Md0FBQUpEazZBaFU1T2dJClZBQUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDQWRaQmMrZVNVV08wUHlGOUJNK200Q1RmZ0tqM295YXg0cGhicEh6YkpPTHcKQUFBRUFNL1BQZytFRUl6eEdGbTNYS3hiOWJNOTdJRXJUd3dFRWF4cmxaMWVjaWFSMWtGejU1SlJZN1EvSVgwRXo2YmdKTgorQXFQZWpKckhpbUZ1a2ZOc2s0dkFBQUFCa0Z5WjI5RFJBRUNBd1FGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K"
stringData:  
  type: git
  url:  git@github.com:gclamigueiro/calculator-microservices