apiVersion: v1
kind: Secret
metadata:
  labels:
    argocd.argoproj.io/secret-type: repository
  name: github-repository-secret
  namespace: argocd
type: Opaque
data:
  sshPrivateKey: "HERE THE PRIVATE KEY ENCODED IN BASE 64"
stringData:  
  type: git
  url:  git@github.com:gclamigueiro/calculator-microservices
