apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.Values.name}}-cfg
    namespace: {{ .Values.namespace }}
data:
    PORT: "{{ .Values.config.port }}"
    URI_SUM_SERVICE: "http://sum-svc-gokit-svc:8080/"
    URI_SUBTRACT_SERVICE: "http://subtract-svc-gokit-svc:8080/"


