apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: multiple-operation-svc-go-kit-ing-test
  namespace: dev 
  annotations:
    ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: minikube-cluster.com.tech
    - http:
        paths:
          - path: /v1/calculator/multiple-operation-test
            pathType: Prefix
            backend:
              service:
                name: multiple-operation-svc-go-kit-svc
                port:
                  number: 8080            
