apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ing
  annotations:
    ingress.kubernetes.io/rewrite-target: /

spec:
  rules:
    - host: "minikube-cluster.com"  
    - http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              service:
                name: {{ .Values.name }}-svc
                port: {{ .Values.config.port }}


