apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sum-svc-gokit-dev
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: https://kubernetes.default.svc
  project: calculator-services-dev
  source:
    helm:
      valueFiles:
      - values-dev.yaml
    path: ./sum-svc-gokit/iaas/helm
    repoURL: git@github.com:gclamigueiro/calculator-microservices
    targetRevision: develop