
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.name }}
  name: {{ .Values.name }}-deploy
  namespace: {{ .Values.namespace }}  
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.name }}
      app.kubernetes.io/version: "1.0.0"
      app.kubernetes.io/component: services
      app.kubernetes.io/part-of: calculator
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Values.name }}
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: services
        app.kubernetes.io/part-of: calculator
    spec:
      containers:
      - image: gcamps/{{ .Values.name }}:latest
        imagePullPolicy: IfNotPresent
        name: {{ .Values.name }}
        resources:
          requests:
            cpu: 50m
            memory: 256Mi